---
apiVersion: apps/v1
kind: Deployment
metadata:
     name: aptenv-deploy
spec:
     replicas: 1
     selector:
          matchLabels:
               app: aptenv-pod
     template:
          metadata:
               labels: 
                    app: aptenv-pod               
          spec:
               containers:
                    - name: aptenv-app
                      image: robinrrr10/aptenv
                      ports:
                           - containerPort: 8080
                      env:
                           - name: ename
                             valueFrom:
                                  configMapKeyRef:
                                       name: apt-config
                                       key: ename
                           - name: configenvone
                             valueFrom:
                                  configMapKeyRef:
                                       name: apt-config
                                       key: configenv1
---
apiVersion: v1
kind: Service
metadata:
     name: aptenv-svc
spec:
     type: NodePort
     ports:
           - nodePort: 31002
             port: 8080
             targetPort: 8080
     selector:
           app: aptenv-pod