---
apiVersion: apps/v1
kind: Deployment
metadata:
     name: aptenv-deploy
spec:
     replicas: 1
     selector:
          matchLabels:
               app: aptenv-pod
     template:
          metadata:
               labels: 
                    app: aptenv-pod               
          spec:
               containers:
                    - name: aptenv-app
                      image: robinrrr10/aptenv
                      ports:
                           - containerPort: 8080
                      volumeMounts:
                           - mountPath: /all-config
                             name: config-vol
                      envFrom:
                           - configMapRef:
                                  name: apt-config
               volumes:
                    - name: config-vol
                      configMap:
                           name: apt-config
                           items:
                                - key: aptenv.config
                                  path: apt.conf
---
apiVersion: v1
kind: Service
metadata:
     name: aptenv-svc
spec:
     type: NodePort
     ports:
           - nodePort: 31002
             port: 8080
             targetPort: 8080
     selector:
           app: aptenv-pod